USE ROLE ACCOUNTADMIN;

USE DATABASE COFFEE;

USE SCHEMA COFFEE_SHOP;

ALTER TABLE products SET DATA_RETENTION_TIME_IN_DAYS=90;

ALTER TABLE clients SET DATA_RETENTION_TIME_IN_DAYS=90;

ALTER TABLE transactions SET DATA_RETENTION_TIME_IN_DAYS=90;

ALTER TABLE transactions_details SET DATA_RETENTION_TIME_IN_DAYS=90;

SHOW TABLES;

SELECT "name","database_name","kind","is_external","is_hybrid"
FROM TABLE (result_scan(last_query_id()));