USE ROLE ACCOUNTADMIN;

USE DATABASE COFFEE;

USE SCHEMA COFFEE_SHOP;

CREATE OR REPLACE SHARE products_share;
GRANT USAGE ON DATABASE COFFEE TO SHARE products_share;

GRANT USAGE ON SCHEMA COFFEE_SHOP TO SHARE products_share;

GRANT SELECT ON TABLE PRODUCTS TO SHARE products_share;

ALTER SHARE products_share ADD ACCOUNTS = ;