USE ROLE ACCOUNTADMIN;

USE DATABASE COFFEE;

USE SCHEMA COFFEE_SHOP;

SELECT * FROM CLIENTS;

--INSERT INTO clients VALUES(21,'Jack Rincon','jkc@len.com');


--SELECT * FROM clients AT(OFFSET=>-60);


--CREATE OR REPLACE TABLE clients_clone CLONE CLIENTS AT(OFFSET=>-60*100);

--SELECT * FROM CLIENTS_CLONE;

--DROP TABLE CLIENTS;

--ALTER TABLE CLIENTS_CLONE RENAME TO CLIENTS;